name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0 # Flutter 3.19+ destekler (seninki 3.7.2 ise bu da olur)

dependencies:
  
  flutter:
    sdk: flutter

  # ğŸ§  Durumu saklamak iÃ§in
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  app_links: ^4.0.0


  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 

  # ğŸ”€ Sayfa geÃ§iÅŸleri iÃ§in
  go_router: ^13.0.1

  # ğŸ§ª State management
  flutter_riverpod: ^2.4.5
  webview_flutter: ^4.4.1


  # ğŸ”¤ iOS ikonlarÄ± iÃ§in
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  
